package app.soundtree.data.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents a user-designated backup destination.
 *
 * ## Schema history
 * - v8:   Initial schema. `volume_uuid` was the PRIMARY KEY (natural key).
 *         Columns: volume_uuid, on_connect_enabled, scheduled_enabled,
 *         interval_hours, last_backup_at, backup_dir_uri, backup_preferences.
 * - v11:  Added volume_label (nullable).
 * - v12:  Added export_metadata_enabled.
 * - v16:  **Surrogate-key refactor.**
 *         - Introduced `id` (AUTOINCREMENT) as the new PRIMARY KEY.
 *         - Demoted `volume_uuid` to a nullable attribute.
 *         - Added UNIQUE index on `backup_dir_uri` — a SAF tree URI is globally
 *           unique, so no two targets may ever point at the same directory
 *           regardless of volume. This also correctly handles nullable
 *           volume_uuid rows, because the URI uniqueness check is independent
 *           of the UUID.
 *
 * ## Triggers
 * Two independent backup triggers can be enabled in any combination:
 *  - **On connect** ([onConnectEnabled]): fires via [app.soundtree.receiver.StorageMountReceiver]
 *    each time the volume mounts.
 *  - **Scheduled** ([scheduledEnabled] + [intervalHours]): a WorkManager
 *    [androidx.work.PeriodicWorkRequest] fires every [intervalHours] hours.
 *
 * Both default to enabled so the out-of-the-box experience is "back up on
 * connect AND on a 24-hour schedule."
 */
@Entity(
    tableName = "backup_targets",
    indices = [
        Index(value = ["backup_dir_uri"], unique = true),
    ]
)
data class BackupTargetEntity(

    /**
     * Surrogate primary key. Auto-generated by SQLite; never reused after deletion.
     * Used as the stable identity for WorkManager job names, notification IDs,
     * and the [app.soundtree.data.entities.BackupLogEntity.backupTargetId] FK.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Long = 0,

    /**
     * Volume UUID of the backup destination, or null for SAF-only targets
     * where no volume UUID could be parsed from the tree URI.
     *
     * Format matches [app.soundtree.storage.StorageVolumeHelper]:
     *  - [app.soundtree.storage.StorageVolumeHelper.UUID_PRIMARY] ("primary")
     *    for the primary external storage.
     *  - A removable-volume UUID string (e.g. "1A2B-3C4D") for SD cards /
     *    USB drives.
     *  - null when the URI's document-id prefix doesn't encode a volume UUID.
     *
     * Used by [app.soundtree.receiver.StorageMountReceiver] to match a
     * mounting volume against its configured targets, and by the UI to
     * display the volume identity.
     */
    @ColumnInfo(name = "volume_uuid")
    val volumeUuid: String? = null,

    /**
     * Human-readable OS label for this volume (e.g. "USB Drive", "SD Card").
     * Cached here so the Settings tab can display a name even when the drive
     * is not currently connected. Updated whenever the user first adds the
     * target and again each time a backup runs successfully.
     *
     * Null for targets added before schema v11, or when the OS has never
     * provided a label for this volume.
     */
    @ColumnInfo(name = "volume_label")
    val volumeLabel: String? = null,

    /**
     * When true, [app.soundtree.receiver.StorageMountReceiver] will enqueue
     * a [app.soundtree.worker.BackupWorker] job each time this volume mounts.
     *
     * Default: true.
     */
    @ColumnInfo(name = "on_connect_enabled")
    val onConnectEnabled: Boolean = true,

    /**
     * When true, a WorkManager [androidx.work.PeriodicWorkRequest] is kept
     * live for this target, firing every [intervalHours] hours.
     *
     * Toggling this off cancels the periodic request; toggling it back on
     * re-enqueues it using the stored [intervalHours] value.
     *
     * Default: true.
     */
    @ColumnInfo(name = "scheduled_enabled")
    val scheduledEnabled: Boolean = true,

    /**
     * How often the scheduled backup fires, in hours.
     * Only meaningful when [scheduledEnabled] is true. Preserved when
     * [scheduledEnabled] is toggled off so the value survives a re-enable.
     *
     * Default: 24 (once per day).
     */
    @ColumnInfo(name = "interval_hours")
    val intervalHours: Int = 24,

    /**
     * Epoch milliseconds of the most recent completed backup to this target,
     * or null if a backup has never run. Updated by [app.soundtree.worker.BackupWorker]
     * on successful completion. Used for the "Last backed up: …" label in the UI.
     */
    @ColumnInfo(name = "last_backup_at")
    val lastBackupAt: Long? = null,

    /**
     * Persisted SAF (Storage Access Framework) URI string pointing to the
     * user-chosen directory on this volume where backup files will be written.
     *
     * Obtained via [android.content.Intent.ACTION_OPEN_DOCUMENT_TREE] and
     * persisted with [android.content.ContentResolver.takePersistableUriPermission]
     * so access survives process death and device reboots.
     *
     * Null means the user has not yet completed directory selection — the UI
     * should treat this target as incomplete and prompt for a directory before
     * allowing backup to run. Set during the add-target flow.
     *
     * Subject to a UNIQUE constraint (see [indices] above) — no two targets
     * may point at the same SAF directory.
     */
    @ColumnInfo(name = "backup_dir_uri")
    val backupDirUri: String? = null,

    /**
     * When true, the backup archive will include a snapshot of app preferences
     * (SharedPreferences). **Currently stubbed — has no effect on backup
     * behaviour.** Wired up in a follow-on feature.
     *
     * Default: false (opt-in once the feature is implemented).
     */
    @ColumnInfo(name = "backup_preferences")
    val backupPreferences: Boolean = false,

    /**
     * Whether to write a companion .json metadata file alongside each .m4a
     * during backup. Defaults to false; the user opts in via Settings.
     *
     * Added in schema v12.
     */
    @ColumnInfo(name = "export_metadata_enabled")
    val exportMetadataEnabled: Boolean = false,
)